server: # REST and WS server
  port: 443 # you can change this if u want
  address: 0.0.0.0 #you can change this too
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "youwillfail"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 100MB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
